[package]
name = "sparusta"
version = "0.1.0"
authors = ["Yuxuan Chen <yuxuanchen1997@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
